import SwiftUI

extension UIColor {
    public static var backgroundSurfacePrimary: UIColor { .green }
    public static var backgroundSurfaceSecondary: UIColor { .green }
    public static var border: UIColor { .green }
    public static var challengeFailed: UIColor { .green }
    public static var challengeInProgress: UIColor { .green }
    public static var challengeNotDone: UIColor { .green }
    public static var challengeSuccess: UIColor { .green }
    public static var clean: UIColor { .green }
    public static var cleanDisabled: UIColor { .green }
    public static var cleanHighlight: UIColor { .green }
    public static var cleanSecondary: UIColor { .green }
    public static var cleanSecondaryDisabled: UIColor { .green }
    public static var cleanSecondaryHighlight: UIColor { .green }
    public static var cta: UIColor { .green }
    public static var ctaDisabled: UIColor { .green }
    public static var ctaHighlight: UIColor { .green }
    public static var graphicalElements1: UIColor { .green }
    public static var graphicalElements2: UIColor { .green }
    public static var graphicalElements3: UIColor { .green }
    public static var graphicalElements4: UIColor { .green }
    public static var graphicalElements5: UIColor { .green }
    public static var graphicalElements6: UIColor { .green }
    public static var graphicalElements7: UIColor { .green }
    public static var navigation: UIColor { .green }
    public static var nonText: UIColor { .green }
    public static var onBackgroundDisabled: UIColor { .green }
    public static var onBackgroundDisabledOff: UIColor { .green }
    public static var onBackgroundDisabledOn: UIColor { .green }
    public static var onBackgroundEnabledOff: UIColor { .green }
    public static var onBackgroundEnabledOn: UIColor { .green }
    public static var onClean: UIColor { .green }
    public static var onCleanDisabled: UIColor { .green }
    public static var onCleanSecondary: UIColor { .green }
    public static var onCleanSecondaryDisabled: UIColor { .green }
    public static var onCta: UIColor { .green }
    public static var onCtaDisabled: UIColor { .green }
    public static var onNonText: UIColor { .green }
    public static var onPrimary: UIColor { .green }
    public static var onPrimaryDisabled: UIColor { .green }
    public static var onRewards: UIColor { .green }
    public static var onSecondary: UIColor { .green }
    public static var onSecondaryDisabled: UIColor { .green }
    public static var onSignal: UIColor { .green }
    public static var onSurfaceDisabled: UIColor { .green }
    public static var onSurfaceDisabledOff: UIColor { .green }
    public static var onSurfaceDisabledOn: UIColor { .green }
    public static var onSurfaceEnabledOff: UIColor { .green }
    public static var onSurfaceEnabledOn: UIColor { .green }
    public static var onWaitlist: UIColor { .green }
    public static var onWaitlistDisabled: UIColor { .green }
    public static var primary: UIColor { .green }
    public static var primaryDisabled: UIColor { .green }
    public static var primaryHighlight: UIColor { .green }
    public static var secondary: UIColor { .green }
    public static var secondaryDisabled: UIColor { .green }
    public static var secondaryHighlight: UIColor { .green }
//    public static var skeleton: UIColor { .green }
    public static var signalDelete: UIColor { .green }
    public static var signalDeleteBackground: UIColor { .green }
    public static var signalDeleteText: UIColor { .green }
    public static var signalErrorBackground: UIColor { .green }
    public static var signalErrorText: UIColor { .green }
    public static var signalSuccessBackground: UIColor { .green }
    public static var signalSuccessText: UIColor { .green }
    public static var signalWarningBackground: UIColor { .green }
    public static var signalWarningText: UIColor { .green }
    public static var tabs: UIColor { .green }
    public static var waitlist: UIColor { .green }
    public static var waitlistBackground: UIColor { .green }
    public static var waitlistDisabled: UIColor { .green }
    public static var waitlistHighlight: UIColor { .green }
    public static var waitlistText: UIColor { .green }
}
