version: 2.1

parameters:
  xcode-version:
    type: string
    default: "14.1.0"
  simulator-version:
    type: string
    default: "16.1"
  simulator-device:
    type: string
    default: "iPhone 14 Pro"
  ruby-version:
    type: string
    default: "3.1.2"

orbs:
  macos: circleci/macos@2

commands:
  setup-and-run-lane:
    description: "All the common steps needed to build and deploy the different schemes."
    parameters:
      lane:
        type: string
    steps:
      - macos/switch-ruby:
          version: << pipeline.parameters.ruby-version >>
      - macos/preboot-simulator:
          version: << pipeline.parameters.simulator-version >>
          platform: "iOS"
          device: << pipeline.parameters.simulator-device >>
      - checkout
      - run: cd DemoApp; bundle install
      - run:
          name: Fastlane
          command: cd DemoApp; bundle exec fastlane << parameters.lane >>

jobs:
  run-tests:
    macos:
      xcode: << pipeline.parameters.xcode-version >>
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run: brew install swiftlint
      - setup-and-run-lane:
          lane: "pr"
      - run:
          name: "Handle test output"
          command: cd DemoApp; bundle exec fastlane handle_test_output
          when: always
      - store_artifacts:
          path: DemoApp/fastlane/test_output.zip
      - store_test_results:
          path: DemoApp/fastlane/test_output

  build-and-deploy-demo-app:
    macos:
      xcode: << pipeline.parameters.xcode-version >>
    steps:
      - setup-and-run-lane:
          lane: "demo_app"

workflows:
  pr-test:
    jobs:
      - run-tests:
          filters:
            branches:
              ignore: /^main/

  publish-demo-app:
    jobs:
      - build-and-deploy-demo-app:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
