trigger: none

pr:
  autoCancel: true
  branches:
    include:
      - main

variables:
  - group: "SatsVariables"
  - name: "scheme"
    value: "DemoApp"
  - name: "sdk"
    value: "iphoneos"
  - name: "iOSVersion"
    value: "15.0"

pool:
  vmImage: "macos-latest"

jobs:
  - job: BuildDev
    displayName: Build SATS Dev
    steps:
      - task: InstallSSHKey@0
        displayName: "Install SSH key for SATSType"
        inputs:
          knownHostsEntry: $(SATSCore_GITHUB_HOST)
          sshPublicKey: $(SATSType_SSH_DEPLOY_PUBLIC_KEY)
          sshKeySecureFile: "SATSType_SSH_DEPLOY_KEY"

      - task: Bash@3
        displayName: "Workaround for private SSH SPM dependencies"
        inputs:
          targetType: "inline"
          script: "for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan -t ecdsa github.com,$ip; done 2>/dev/null >> ~/.ssh/known_hosts"
          failOnStderr: true

      - task: Xcode@5
        displayName: "Xcode Test"
        inputs:
          actions: "test"
          sdk: "$(sdk)"
          scheme: "$(scheme)"
          xcodeVersion: "default"
          xcWorkspacePath: "DemoApp/DemoApp.xcodeproj"
          destinationPlatform: "iOS"
          signingOption: "auto"
          args: "-UseModernBuildSystem=YES"
          destinationPlatformOption: "iOS"
          destinationSimulators: "iPhone 13 Pro,OS=$(iOSVersion)"
          workingDirectory: "DemoApp"
          useXcpretty: true
          publishJUnitResults: true
